name: Publish Docker image

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ vars.DOCKER_REGISTRY }}

    steps:
      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          # list of Docker images to use as base name for tags
          images: ${{ vars.DOCKER_REGISTRY }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=latest
            type=sha
