name: docker login

on:
  workflow_dispatch:
  push:

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1
        with:
          buildkitd-config-inline: ${{ vars.BUILDX_CONFIG }}

      # https://github.com/docker/login-action
      - name: Login to DockerHub
        #if: ${{ secrets.DOCKER_USERNAME != '' }}
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # https://github.com/docker/login-action
      - name: Login to registry
        env:
          DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
        if: ${{ env.DOCKER_REGISTRY != '' }}
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
